name: 'Madge Circular Dependency Check'
description: 'Checks for circular dependencies using Madge'

inputs:
  entry-point:
    description: 'Entry point for Madge to start checking'
    required: false
    default: 'src/index.ts'

runs:
  using: "composite"
  steps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Madge
      run: npm install -g madge

    - name: Check if package.json exists
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "package.json"

    - name: Install dependencies
      if: steps.check_files.outputs.files_exists == 'true'
      run: npm install

    - name: Run Madge circular dependency check
      run: |
        chmod +x .github/scripts/madge.bash
        .github/scripts/madge.bash

# Optional Madge check job
  madge-check:
    needs: build  # This ensures the Madge check runs after the build job
    uses: ./.github/workflows/madge-check.yml