name: Circular Dependency Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  madge-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Madge
      run: npm install -g madge

    - name: Check if package.json exists
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "package.json"

    - name: Install dependencies
      if: steps.check_files.outputs.files_exists == 'true'
      run: npm install

    - name: Run Madge circular dependency check
      run: |
        chmod +x .github/scripts/madge.sh
        .github/scripts/madge.sh