name: Main Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm ci

  # Optional Madge check job
  madge-check:
    needs: setup  # This ensures the Madge check runs after the build job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Madge Check
      uses: ./.github/actions/madge-check